/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/activations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activations */
        get: operations["activations_api_v1_activations_get"];
        put?: never;
        /** Create Activation */
        post: operations["create_activation_api_v1_activations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activations/{activation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activation */
        get: operations["activation_api_v1_activations__activation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activations/{activation_id}/control-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Control Preview */
        post: operations["control_preview_api_v1_activations__activation_id__control_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activations/{activation_id}/exit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exit Strategy */
        post: operations["exit_strategy_api_v1_activations__activation_id__exit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activations/{activation_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Plan Activation */
        post: operations["resume_plan_activation_api_v1_activations__activation_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activations/{activation_id}/stop-new-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop New Risk */
        post: operations["stop_new_risk_api_v1_activations__activation_id__stop_new_risk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activations/{activation_id}/takeover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User Takeover */
        post: operations["user_takeover_api_v1_activations__activation_id__takeover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activations/{activation_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activation Timeline */
        get: operations["activation_timeline_api_v1_activations__activation_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Context */
        get: operations["market_context_api_v1_market_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Window */
        get: operations["market_window_api_v1_market_window_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order-schedules/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Order Schedule Preview */
        post: operations["order_schedule_preview_api_v1_order_schedules_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan-versions/{plan_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan Version */
        get: operations["plan_version_api_v1_plan_versions__plan_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan-versions/{plan_version_id}/activation-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activation Preview */
        post: operations["activation_preview_api_v1_plan_versions__plan_version_id__activation_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plans */
        get: operations["plans_api_v1_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_v1_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan */
        get: operations["plan_api_v1_plans__plan_id__get"];
        /** Update Plan */
        put: operations["update_plan_api_v1_plans__plan_id__put"];
        post?: never;
        /** Delete Plan */
        delete: operations["delete_plan_api_v1_plans__plan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/fix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fix Plan */
        post: operations["fix_plan_api_v1_plans__plan_id__fix_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receipt */
        get: operations["receipt_api_v1_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews */
        get: operations["reviews_api_v1_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review */
        get: operations["review_api_v1_reviews__review_id__get"];
        /** Refresh Review */
        put: operations["refresh_review_api_v1_reviews__review_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Review */
        post: operations["complete_review_api_v1_reviews__review_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings Status */
        get: operations["settings_status_api_v1_settings_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/test-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Email */
        post: operations["test_email_api_v1_settings_test_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategies */
        get: operations["strategies_api_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategy Schema */
        get: operations["strategy_schema_api_v1_strategies__strategy_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivationPayload */
        ActivationPayload: {
            /** Expected Schedule Digest */
            expected_schedule_digest?: string | null;
            /** Plan Version Id */
            plan_version_id: string;
        };
        /** AmountDistribution */
        AmountDistribution: {
            /**
             * Base Notional
             * @default 10
             */
            base_notional: string;
            /**
             * Custom Notionals
             * @default []
             */
            custom_notionals: string[];
            /** @default LOW_TO_HIGH */
            direction: components["schemas"]["DistributionDirection"];
            /**
             * Exponential Ratio
             * @default 2
             */
            exponential_ratio: string;
            /**
             * Linear Step
             * @default 10
             */
            linear_step: string;
            /** @default FIXED */
            mode: components["schemas"]["AmountDistributionMode"];
        };
        /**
         * AmountDistributionMode
         * @enum {string}
         */
        AmountDistributionMode: "FIXED" | "LINEAR" | "EXPONENTIAL" | "CUSTOM";
        /**
         * BinancePriceMatch
         * @enum {string}
         */
        BinancePriceMatch: "OPPONENT" | "OPPONENT_5" | "OPPONENT_10" | "OPPONENT_20" | "QUEUE" | "QUEUE_5" | "QUEUE_10" | "QUEUE_20";
        /** CancelOnShockRule */
        CancelOnShockRule: {
            /** Adverse Move Bps */
            adverse_move_bps: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "CANCEL_ON_SHOCK";
            /**
             * Max Triggers
             * @default 1
             */
            max_triggers: number;
            /** Window Seconds */
            window_seconds: number;
        };
        /** CompiledOrderLeg */
        CompiledOrderLeg: {
            /** Effective Notional */
            effective_notional: string;
            /** Leg Count */
            leg_count: number;
            /** Leg Index */
            leg_index: number;
            /** Price */
            price: string | null;
            /** Quantity */
            quantity: string;
            /** Raw Price */
            raw_price: string | null;
            /** Requested Notional */
            requested_notional: string;
            /** Sizing Price */
            sizing_price: string;
        };
        /** ConditionGroup */
        ConditionGroup: {
            /**
             * Items
             * @default [
             *       {
             *         "kind": "DECISION_BASIS_READY"
             *       }
             *     ]
             */
            items: (components["schemas"]["DecisionBasisReadyCondition"] | components["schemas"]["MarkPriceCondition"] | components["schemas"]["SpreadBpsCondition"] | components["schemas"]["PriceMoveBpsCondition"] | components["schemas"]["ProfitRCondition"] | components["schemas"]["ElapsedCondition"])[];
            /** @default ALL */
            operator: components["schemas"]["ConditionOperator"];
        };
        /**
         * ConditionOperator
         * @enum {string}
         */
        ConditionOperator: "ALL" | "ANY";
        /**
         * ControlIntent
         * @enum {string}
         */
        ControlIntent: "STOP_NEW_RISK" | "RESUME_ACTIVATION" | "EXIT_STRATEGY" | "USER_TAKEOVER";
        /** ControlPayload */
        ControlPayload: {
            /** Expected Version */
            expected_version: number;
            /** Takeover Scope */
            takeover_scope?: {
                [key: string]: unknown;
            };
        };
        /**
         * DecisionBasisKind
         * @enum {string}
         */
        DecisionBasisKind: "STRATEGY_SIGNAL" | "DIRECT_EXECUTION";
        /** DecisionBasisReadyCondition */
        DecisionBasisReadyCondition: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "DECISION_BASIS_READY";
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "LONG" | "SHORT";
        /**
         * DistributionDirection
         * @enum {string}
         */
        DistributionDirection: "LOW_TO_HIGH" | "HIGH_TO_LOW";
        /** DraftDecisionBasis */
        DraftDecisionBasis: {
            /** Decision Basis Ref */
            decision_basis_ref: string;
            kind: components["schemas"]["DecisionBasisKind"];
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
        };
        /** ElapsedCondition */
        ElapsedCondition: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ELAPSED_SECONDS";
            /** Minimum Seconds */
            minimum_seconds: number;
        };
        /**
         * EvaluationResult
         * @enum {string}
         */
        EvaluationResult: "AS_EXPECTED" | "ISSUE_FOUND" | "UNKNOWN" | "NOT_APPLICABLE";
        /** ExpireRemainingRule */
        ExpireRemainingRule: {
            /** After Seconds */
            after_seconds: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "EXPIRE_REMAINING";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitialStopSpec */
        InitialStopSpec: {
            /** @default EACH_CONFIRMED_FILL */
            coverage: components["schemas"]["StopCoverage"];
            /** Distance Bps */
            distance_bps: string;
            /** @default MARK_PRICE */
            trigger_source: components["schemas"]["StopTriggerSource"];
        };
        /** InstrumentOrderRules */
        InstrumentOrderRules: {
            /** Limit Quantity Step */
            limit_quantity_step: string;
            /** Market Quantity Step */
            market_quantity_step: string;
            /** Max Limit Quantity */
            max_limit_quantity: string;
            /** Max Market Quantity */
            max_market_quantity: string;
            /** Max Price */
            max_price: string;
            /** Min Limit Quantity */
            min_limit_quantity: string;
            /** Min Market Quantity */
            min_market_quantity: string;
            /** Min Notional */
            min_notional: string;
            /** Min Price */
            min_price: string;
            /** Price Tick Size */
            price_tick_size: string;
            /** Source */
            source: string;
            /** Source Cutoff */
            source_cutoff: string;
        };
        /** MarkPriceCondition */
        MarkPriceCondition: {
            /**
             * Comparator
             * @enum {string}
             */
            comparator: "GTE" | "LTE";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "MARK_PRICE";
            /** Price */
            price: string;
        };
        /** MarketBar */
        MarketBar: {
            /** Close */
            close: string;
            /**
             * Close At
             * Format: date-time
             */
            close_at: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Open */
            open: string;
            /**
             * Open At
             * Format: date-time
             */
            open_at: string;
            /** Volume */
            volume: string;
        };
        /** MarketContext */
        MarketContext: {
            /** Ask Price */
            ask_price: string;
            /** Atr 14 */
            atr_14: string;
            /** Bid Price */
            bid_price: string;
            /** Channel Lookback 15M */
            channel_lookback_15m: number;
            /** Channel Lower */
            channel_lower: string;
            /** Channel Upper */
            channel_upper: string;
            /** Instrument Ref */
            instrument_ref: string;
            /** Latest Close 15M */
            latest_close_15m: string;
            /** Latest Close 1M */
            latest_close_1m: string;
            /**
             * Latest Closed 15M At
             * Format: date-time
             */
            latest_closed_15m_at: string;
            /**
             * Latest Closed 1M At
             * Format: date-time
             */
            latest_closed_1m_at: string;
            /** Latest Trade Count 1M */
            latest_trade_count_1m: number;
            /** Latest Volume 1M */
            latest_volume_1m: string;
            /** Long Breakout Gap Pct */
            long_breakout_gap_pct: string;
            /** Reference Price */
            reference_price: string;
            /** Short Breakout Gap Pct */
            short_breakout_gap_pct: string;
            /** Source */
            source: string;
            /**
             * Source Cutoff
             * Format: date-time
             */
            source_cutoff: string;
        };
        /** MarketWindow */
        MarketWindow: {
            /** Bars */
            bars: components["schemas"]["MarketBar"][];
            /** Instrument Ref */
            instrument_ref: string;
            /**
             * Interval
             * @enum {string}
             */
            interval: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
            /** Source */
            source: string;
            /**
             * Source Cutoff
             * Format: date-time
             */
            source_cutoff: string;
        };
        /**
         * NumericComparator
         * @enum {string}
         */
        NumericComparator: "GTE" | "LTE" | "ABS_GTE";
        /** OrderSchedulePreview */
        OrderSchedulePreview: {
            /** Compiler Version */
            compiler_version: string;
            direction: components["schemas"]["Direction"];
            /** Effective Total Notional */
            effective_total_notional: string;
            /** Instrument Ref */
            instrument_ref: string;
            instrument_rules: components["schemas"]["InstrumentOrderRules"];
            /** Instrument Rules Digest */
            instrument_rules_digest: string;
            /** Issues */
            issues: components["schemas"]["ScheduleIssue"][];
            /** Legs */
            legs: components["schemas"]["CompiledOrderLeg"][];
            /** Max Notional */
            max_notional: string;
            /** Normalized Legs */
            normalized_legs: components["schemas"]["CompiledOrderLeg"][];
            /** Preprotected Parallel Supported */
            preprotected_parallel_supported: boolean;
            /** Reference Price */
            reference_price: string | null;
            /** Requested Total Notional */
            requested_total_notional: string;
            /** Schedule Digest */
            schedule_digest: string;
            /** Schedule Ref */
            schedule_ref: string;
            schedule_spec: components["schemas"]["OrderScheduleSpec"];
            /** Source Cutoff */
            source_cutoff: string;
            /** Valid */
            valid: boolean;
            /** Venue Ref */
            venue_ref: string;
        };
        /** OrderSchedulePreviewPayload */
        OrderSchedulePreviewPayload: {
            /** @default DIRECT_EXECUTION */
            decision_basis_kind: components["schemas"]["DecisionBasisKind"];
            direction: components["schemas"]["Direction"];
            /** Instrument Ref */
            instrument_ref: string;
            /** Max Notional */
            max_notional: string;
            /** Reference Price */
            reference_price?: string | null;
            /** Schedule Ref */
            schedule_ref: string;
            spec: components["schemas"]["OrderScheduleSpec"];
            /**
             * Venue Ref
             * @default BINANCE_USDM
             */
            venue_ref: string;
        };
        /** OrderScheduleSpec */
        OrderScheduleSpec: {
            amount_distribution: components["schemas"]["AmountDistribution"];
            /**
             * Dynamic Rules
             * @default []
             */
            dynamic_rules: (components["schemas"]["CancelOnShockRule"] | components["schemas"]["ExpireRemainingRule"] | components["schemas"]["SteppedProtectionRule"])[];
            /**
             * @default {
             *       "items": [
             *         {
             *           "kind": "DECISION_BASIS_READY"
             *         }
             *       ],
             *       "operator": "ALL"
             *     }
             */
            entry_conditions: components["schemas"]["ConditionGroup"];
            /** Price Distribution */
            price_distribution: components["schemas"]["SinglePrice"] | components["schemas"]["PriceDistribution"];
            protection_policy?: components["schemas"]["ProtectionPolicy"] | null;
            /** @default SERIAL_PROTECTED */
            submission_mode: components["schemas"]["ScheduleSubmissionMode"];
            /** @default LOW_TO_HIGH */
            submission_order: components["schemas"]["ScheduleSubmissionOrder"];
            /**
             * @default {
             *       "order_type": "LIMIT",
             *       "post_only": false,
             *       "time_in_force": "GTC"
             *     }
             */
            venue_policy: components["schemas"]["VenueOrderPolicy"];
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Account Id */
            account_id: string;
            /** Authority Class */
            authority_class: string;
            /** Database Name */
            database_name: string;
            /** Environment Id */
            environment_id: string;
            /** Environment Kind */
            environment_kind: string;
            /** Open Activation Count */
            open_activation_count: number;
            /** Profile */
            profile: string;
            /** Runtime Real Write Gate */
            runtime_real_write_gate: string;
            /** Server Fact Cutoff */
            server_fact_cutoff: string;
            /** View Retrieved At */
            view_retrieved_at: string;
        };
        /** PlanCreatePayload */
        PlanCreatePayload: {
            creator_kind: components["schemas"]["PlanCreatorKind"];
            decision_basis?: components["schemas"]["DraftDecisionBasis"] | null;
            /** Direction */
            direction: string;
            /** Instrument Ref */
            instrument_ref: string;
            /** Max Allowed Loss */
            max_allowed_loss: string;
            /** Max Margin */
            max_margin: string;
            /** Max Notional */
            max_notional: string;
            order_schedule_spec?: components["schemas"]["OrderScheduleSpec"] | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Plan Name */
            plan_name: string;
            /** Strategy Id */
            strategy_id?: string | null;
            /** Target Exposure */
            target_exposure: string;
            /** Valid Minutes */
            valid_minutes: number;
            /**
             * Venue Ref
             * @default BINANCE_USDM
             */
            venue_ref: string;
        };
        /**
         * PlanCreatorKind
         * @enum {string}
         */
        PlanCreatorKind: "HUMAN" | "AI";
        /** PlanDraftPayload */
        PlanDraftPayload: {
            decision_basis?: components["schemas"]["DraftDecisionBasis"] | null;
            /** Direction */
            direction: string;
            /** Instrument Ref */
            instrument_ref: string;
            /** Max Allowed Loss */
            max_allowed_loss: string;
            /** Max Margin */
            max_margin: string;
            /** Max Notional */
            max_notional: string;
            order_schedule_spec?: components["schemas"]["OrderScheduleSpec"] | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Plan Name */
            plan_name: string;
            /** Strategy Id */
            strategy_id?: string | null;
            /** Target Exposure */
            target_exposure: string;
            /** Valid Minutes */
            valid_minutes: number;
            /**
             * Venue Ref
             * @default BINANCE_USDM
             */
            venue_ref: string;
        };
        /** PriceDistribution */
        PriceDistribution: {
            /**
             * Custom Gap Weights
             * @default []
             */
            custom_gap_weights: string[];
            /**
             * Geometric Ratio
             * @default 2
             */
            geometric_ratio: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "LADDER";
            /** Level Count */
            level_count: number;
            /**
             * Linear Start Weight
             * @default 1
             */
            linear_start_weight: string;
            /**
             * Linear Step
             * @default 1
             */
            linear_step: string;
            /** Lower Price */
            lower_price: string;
            /** @default LOW_TO_HIGH */
            spacing_direction: components["schemas"]["DistributionDirection"];
            /** @default EQUAL */
            spacing_mode: components["schemas"]["PriceSpacingMode"];
            /** Upper Price */
            upper_price: string;
        };
        /** PriceMoveBpsCondition */
        PriceMoveBpsCondition: {
            comparator: components["schemas"]["NumericComparator"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PRICE_MOVE_BPS";
            /** Threshold Bps */
            threshold_bps: string;
            /** Window Seconds */
            window_seconds: number;
        };
        /**
         * PriceSpacingMode
         * @enum {string}
         */
        PriceSpacingMode: "EQUAL" | "LINEAR" | "GEOMETRIC" | "CUSTOM_WEIGHTS";
        /** ProfitRCondition */
        ProfitRCondition: {
            /**
             * Comparator
             * @enum {string}
             */
            comparator: "GTE" | "LTE";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PROFIT_R";
            /** Threshold R */
            threshold_r: string;
        };
        /** ProtectionPolicy */
        ProtectionPolicy: {
            initial_stop: components["schemas"]["InitialStopSpec"];
            take_profit_ladder?: components["schemas"]["TakeProfitLadderSpec"] | null;
            /** Time Exit Seconds */
            time_exit_seconds?: number | null;
        };
        /** ProtectionStep */
        ProtectionStep: {
            /** Stop R */
            stop_r: string;
            /** Trigger R */
            trigger_r: string;
        };
        /** ReviewCompletionPayload */
        ReviewCompletionPayload: {
            conclusion: components["schemas"]["EvaluationResult"];
            /** Expected Version */
            expected_version: number;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ReviewRefreshPayload */
        ReviewRefreshPayload: {
            /** Expected Version */
            expected_version: number;
        };
        /** ScheduleIssue */
        ScheduleIssue: {
            /** Code */
            code: string;
            /** Field */
            field: string;
            /** Leg Index */
            leg_index?: number | null;
        };
        /**
         * ScheduleSubmissionMode
         * @enum {string}
         */
        ScheduleSubmissionMode: "SERIAL_PROTECTED" | "PREPROTECTED_PARALLEL";
        /**
         * ScheduleSubmissionOrder
         * @enum {string}
         */
        ScheduleSubmissionOrder: "LOW_TO_HIGH" | "HIGH_TO_LOW";
        /** SettingsStatusResponse */
        SettingsStatusResponse: {
            /** Account Id */
            account_id: string;
            /** App Executor Product Build Consistent */
            app_executor_product_build_consistent: boolean | null;
            /** Authority Class */
            authority_class: string;
            /** Authorized Activation Id */
            authorized_activation_id: string | null;
            /** Bind */
            bind: string;
            /** Configured Runtime Real Write Gate */
            configured_runtime_real_write_gate: string;
            /** Database Available */
            database_available: boolean;
            /** Database Name */
            database_name: string;
            /** Database Reason Code */
            database_reason_code: string | null;
            /** Email Configuration Status */
            email_configuration_status: string;
            /** Email Delivery Enabled */
            email_delivery_enabled: boolean;
            /** Environment Id */
            environment_id: string;
            /** Environment Kind */
            environment_kind: string;
            /** Executor Status */
            executor_status: string;
            /** Executor Status Checked At */
            executor_status_checked_at: string;
            /** Live Write Gate Violations */
            live_write_gate_violations: string[];
            /** Port */
            port: number;
            /** Product Build Id */
            product_build_id: string;
            /** Profile */
            profile: string;
            /** Runtime Real Write Gate */
            runtime_real_write_gate: string;
            /** Server Fact Cutoff */
            server_fact_cutoff: string | null;
            /** View Retrieved At */
            view_retrieved_at: string;
        };
        /** SinglePrice */
        SinglePrice: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "SINGLE";
            /** Limit Price */
            limit_price?: string | null;
        };
        /** SpreadBpsCondition */
        SpreadBpsCondition: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "SPREAD_BPS";
            /** Maximum Bps */
            maximum_bps: string;
        };
        /** SteppedProtectionRule */
        SteppedProtectionRule: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "STEPPED_PROTECTION";
            /**
             * Max Adjustments
             * @default 8
             */
            max_adjustments: number;
            /**
             * Minimum Update Interval Seconds
             * @default 5
             */
            minimum_update_interval_seconds: number;
            /** Steps */
            steps: components["schemas"]["ProtectionStep"][];
        };
        /**
         * StopCoverage
         * @enum {string}
         */
        StopCoverage: "EACH_CONFIRMED_FILL";
        /**
         * StopTriggerSource
         * @enum {string}
         */
        StopTriggerSource: "MARK_PRICE";
        /** TakeProfitLadderSpec */
        TakeProfitLadderSpec: {
            /** Levels */
            levels: components["schemas"]["TakeProfitLevel"][];
        };
        /** TakeProfitLevel */
        TakeProfitLevel: {
            /** Quantity Fraction */
            quantity_fraction: string;
            /** Trigger R */
            trigger_r: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VenueOrderPolicy */
        VenueOrderPolicy: {
            /** Display Quantity */
            display_quantity?: string | null;
            /** Expire At */
            expire_at?: string | null;
            /** @default LIMIT */
            order_type: components["schemas"]["VenueOrderType"];
            /**
             * Post Only
             * @default false
             */
            post_only: boolean;
            price_match?: components["schemas"]["BinancePriceMatch"] | null;
            /** @default GTC */
            time_in_force: components["schemas"]["VenueTimeInForce"] | null;
        };
        /**
         * VenueOrderType
         * @enum {string}
         */
        VenueOrderType: "LIMIT" | "MARKET";
        /**
         * VenueTimeInForce
         * @enum {string}
         */
        VenueTimeInForce: "GTC" | "GTD" | "IOC" | "FOK";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    activations_api_v1_activations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    create_activation_api_v1_activations_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivationPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activation_api_v1_activations__activation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    control_preview_api_v1_activations__activation_id__control_preview_post: {
        parameters: {
            query: {
                intent: components["schemas"]["ControlIntent"];
            };
            header?: never;
            path: {
                activation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exit_strategy_api_v1_activations__activation_id__exit_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                activation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_plan_activation_api_v1_activations__activation_id__resume_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                activation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_new_risk_api_v1_activations__activation_id__stop_new_risk_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                activation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_takeover_api_v1_activations__activation_id__takeover_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                activation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activation_timeline_api_v1_activations__activation_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_context_api_v1_market_context_get: {
        parameters: {
            query?: {
                instrument_ref?: string;
                channel_lookback_15m?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_window_api_v1_market_window_get: {
        parameters: {
            query: {
                instrument_ref: string;
                start_at: string;
                end_at: string;
                interval?: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketWindow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    order_schedule_preview_api_v1_order_schedules_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderSchedulePreviewPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchedulePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    plan_version_api_v1_plan_versions__plan_version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activation_preview_api_v1_plan_versions__plan_version_id__activation_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plans_api_v1_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    create_plan_api_v1_plans_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_v1_plans__plan_id__put: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDraftPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_v1_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fix_plan_api_v1_plans__plan_id__fix_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receipt_api_v1_receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reviews_api_v1_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    review_api_v1_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_review_api_v1_reviews__review_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRefreshPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_review_api_v1_reviews__review_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCompletionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_status_api_v1_settings_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsStatusResponse"];
                };
            };
        };
    };
    test_email_api_v1_settings_test_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    strategies_api_v1_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    strategy_schema_api_v1_strategies__strategy_id__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
