from __future__ import annotations

from halpha.time_display import DEFAULT_DISPLAY_TIMEZONE

DEFAULT_DASHBOARD_DISPLAY_TIMEZONE = DEFAULT_DISPLAY_TIMEZONE
DEFAULT_DASHBOARD_TIMESTAMP_DATE_ORDER = "year_first"
DEFAULT_DASHBOARD_TIMESTAMP_HOUR_CYCLE = "24h"
DASHBOARD_TIMESTAMP_DATE_ORDER_OPTIONS = ("year_first", "year_last")
DASHBOARD_TIMESTAMP_HOUR_CYCLE_OPTIONS = ("24h", "12h")
